### ISSUE TITLE
Set Up Kanban board

### ISSUE THREAD

**Issue by shahadat3669** [shahadat3669/pokedex#22]
### We prepare a new Kanban board with a GitHub project. Our project link [pokedex board](https://github.com/users/shahadat3669/projects/7). There are two members on our team: [me ](https://github.com/shahadat3669) and [Paul Sáenz Sucre](https://github.com/elafildecolor).

- [x] Create an empty repository for the group project.
- [x] Follow the steps described in [curriculum-tools-copy-projects](https://github.com/microverseinc/curriculum-tools-copy-projects).
- [x] Open the GitHub project (Kanban board) in our team repo.
- [x] Make sure that in the card titles you can see: Student A, Student B, or Student C.
- [x] Make sure that each card starts with [Xpt] - that number indicates the number of points that shows how complex the task is. 1 point = 1 hour of work.
- [x] As our group includes two people - remove all cards with Student C in the title.
- [X] Decide me as Student B and Paul Saenz Sucre as Student A.
- [X] Each of the team members should assign themselves to the correct cards.

**Comment by Reem-lab** [comment]
# Hi Team, 👋🏻👋🏻 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🚀🔥🎉🎉 
<img src="https://media2.giphy.com/media/G7lfJRrvdhtxK8OVGy/giphy.gif"/>

## Highlights ✨✨
- No Linters errors ✅ 
- Great working on the kanban board and assigning the tasks to the cards🔥🚀🎉
- Descriptive PR ✅🔥🔥



## Optional suggestions



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
